clean:
	@mkdir -p midi
	@mv baddies/*.mid midi/. 2>/dev/null || true
	@mv baddies/*.MID midi/. 2>/dev/null || true
	@mv processed_orig/*.mid midi/. 2>/dev/null || true
	@mv processed_orig/*.MID midi/. 2>/dev/null || true
	@rm processed_wav/*.wav 2>/dev/null || true
